const DEMO_USER_ID = 'demo-user'

const daysAgo = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date
}

const daysFromNow = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date
}

const toIso = (date: Date) => date.toISOString()

export const buildDemoData = () => {
  const accounts = [
    {
      id: 'demo-checking',
      userId: DEMO_USER_ID,
      name: 'Chase Total Checking',
      type: 'CHECKING',
      balance: 12450,
      currency: 'USD',
      institution: 'Chase',
      isActive: true,
    },
    {
      id: 'demo-savings',
      userId: DEMO_USER_ID,
      name: 'Ally High Yield Savings',
      type: 'SAVINGS',
      balance: 8400,
      currency: 'USD',
      institution: 'Ally',
      isActive: true,
    },
    {
      id: 'demo-credit',
      userId: DEMO_USER_ID,
      name: 'Visa Signature',
      type: 'CREDIT_CARD',
      balance: -2150,
      currency: 'USD',
      creditLimit: 10000,
      isActive: true,
    },
    {
      id: 'demo-invest',
      userId: DEMO_USER_ID,
      name: 'Fidelity Brokerage',
      type: 'INVESTMENT',
      balance: 5200,
      currency: 'USD',
      institution: 'Fidelity',
      isActive: true,
    },
  ]

  const categories = [
    {
      id: 'cat-housing',
      userId: DEMO_USER_ID,
      name: 'Housing',
      color: '#84CC16',
      icon: '🏠',
    },
    {
      id: 'cat-food',
      userId: DEMO_USER_ID,
      name: 'Food & Dining',
      color: '#10B981',
      icon: '🍽️',
    },
    {
      id: 'cat-transport',
      userId: DEMO_USER_ID,
      name: 'Transportation',
      color: '#3B82F6',
      icon: '🚗',
    },
    {
      id: 'cat-utilities',
      userId: DEMO_USER_ID,
      name: 'Utilities',
      color: '#06B6D4',
      icon: '💡',
    },
    {
      id: 'cat-entertainment',
      userId: DEMO_USER_ID,
      name: 'Entertainment',
      color: '#F59E0B',
      icon: '🎬',
    },
    {
      id: 'cat-shopping',
      userId: DEMO_USER_ID,
      name: 'Shopping',
      color: '#8B5CF6',
      icon: '🛍️',
    },
    {
      id: 'cat-insurance',
      userId: DEMO_USER_ID,
      name: 'Insurance',
      color: '#6366F1',
      icon: '🛡️',
    },
    {
      id: 'cat-gifts',
      userId: DEMO_USER_ID,
      name: 'Gifts',
      color: '#8B5CF6',
      icon: '🎁',
    },
    {
      id: 'cat-subscriptions',
      userId: DEMO_USER_ID,
      name: 'Subscriptions',
      color: '#F59E0B',
      icon: '🔄',
    },
    {
      id: 'cat-salary',
      userId: DEMO_USER_ID,
      name: 'Salary',
      color: '#10B981',
      icon: '💰',
      isIncome: true,
    },
    {
      id: 'cat-investment',
      userId: DEMO_USER_ID,
      name: 'Investment',
      color: '#22C55E',
      icon: '📈',
    },
    {
      id: 'cat-travel',
      userId: DEMO_USER_ID,
      name: 'Travel',
      color: '#F97316',
      icon: '✈️',
    },
    {
      id: 'cat-healthcare',
      userId: DEMO_USER_ID,
      name: 'Healthcare',
      color: '#EF4444',
      icon: '🏥',
    },
  ]

  const transactions = [
    {
      id: 'txn-001',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-salary',
      category: 'Salary',
      amount: 4800,
      description: 'Insight Global Payroll',
      date: toIso(daysAgo(4)),
      type: 'INCOME',
      isRecurring: true,
      tags: ['payroll'],
    },
    {
      id: 'txn-002',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-housing',
      category: 'Housing',
      amount: 1450,
      description: 'Mortgage payment',
      date: toIso(daysAgo(6)),
      type: 'EXPENSE',
      isRecurring: true,
      tags: ['housing'],
    },
    {
      id: 'txn-003',
      userId: DEMO_USER_ID,
      accountId: 'demo-credit',
      categoryId: 'cat-food',
      category: 'Food & Dining',
      amount: 186.42,
      description: 'Whole Foods Market',
      date: toIso(daysAgo(2)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['grocery'],
    },
    {
      id: 'txn-004',
      userId: DEMO_USER_ID,
      accountId: 'demo-credit',
      categoryId: 'cat-transport',
      category: 'Transportation',
      amount: 64.18,
      description: 'Shell Gas Station',
      date: toIso(daysAgo(10)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['fuel'],
    },
    {
      id: 'txn-005',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-utilities',
      category: 'Utilities',
      amount: 120.33,
      description: 'Duke Energy',
      date: toIso(daysAgo(8)),
      type: 'EXPENSE',
      isRecurring: true,
      tags: ['electric'],
    },
    {
      id: 'txn-006',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-subscriptions',
      category: 'Subscriptions',
      amount: 16.99,
      description: 'Netflix',
      date: toIso(daysAgo(5)),
      type: 'EXPENSE',
      isRecurring: true,
      tags: ['streaming'],
    },
    {
      id: 'txn-007',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-subscriptions',
      category: 'Subscriptions',
      amount: 11.99,
      description: 'Spotify',
      date: toIso(daysAgo(12)),
      type: 'EXPENSE',
      isRecurring: true,
      tags: ['music'],
    },
    {
      id: 'txn-008',
      userId: DEMO_USER_ID,
      accountId: 'demo-credit',
      categoryId: 'cat-entertainment',
      category: 'Entertainment',
      amount: 58.75,
      description: 'AMC Theaters',
      date: toIso(daysAgo(9)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['movies'],
    },
    {
      id: 'txn-009',
      userId: DEMO_USER_ID,
      accountId: 'demo-credit',
      categoryId: 'cat-shopping',
      category: 'Shopping',
      amount: 210.4,
      description: 'Target',
      date: toIso(daysAgo(15)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['retail'],
    },
    {
      id: 'txn-010',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-gifts',
      category: 'Gifts',
      amount: 100,
      description: 'Atitude Igreja donation',
      date: toIso(daysAgo(3)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['donation'],
    },
    {
      id: 'txn-011',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-gifts',
      category: 'Gifts',
      amount: 50,
      description: 'Local charity donation',
      date: toIso(daysAgo(25)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['charity'],
    },
    {
      id: 'txn-012',
      userId: DEMO_USER_ID,
      accountId: 'demo-credit',
      categoryId: 'cat-travel',
      category: 'Travel',
      amount: 420.9,
      description: 'Delta Airlines',
      date: toIso(daysAgo(22)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['flight'],
    },
    {
      id: 'txn-013',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-insurance',
      category: 'Insurance',
      amount: 95,
      description: 'State Farm Premium',
      date: toIso(daysAgo(18)),
      type: 'EXPENSE',
      isRecurring: true,
      tags: ['insurance'],
    },
    {
      id: 'txn-014',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-healthcare',
      category: 'Healthcare',
      amount: 40,
      description: 'CVS Pharmacy',
      date: toIso(daysAgo(11)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['health'],
    },
    {
      id: 'txn-015',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-investment',
      category: 'Investment',
      amount: 300,
      description: 'Roth IRA contribution',
      date: toIso(daysAgo(16)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['investment'],
    },
    {
      id: 'txn-016',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-salary',
      category: 'Salary',
      amount: 4650,
      description: 'Insight Global Payroll',
      date: toIso(daysAgo(34)),
      type: 'INCOME',
      isRecurring: true,
      tags: ['payroll'],
    },
    {
      id: 'txn-017',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      categoryId: 'cat-food',
      category: 'Food & Dining',
      amount: 92.6,
      description: 'Sweetgreen',
      date: toIso(daysAgo(28)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['meal'],
    },
    {
      id: 'txn-018',
      userId: DEMO_USER_ID,
      accountId: 'demo-credit',
      categoryId: 'cat-transport',
      category: 'Transportation',
      amount: 38.5,
      description: 'Uber trip',
      date: toIso(daysAgo(20)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['ride-share'],
    },
    {
      id: 'txn-019',
      userId: DEMO_USER_ID,
      accountId: 'demo-checking',
      amount: 72,
      description: 'Pending merchant',
      date: toIso(daysAgo(7)),
      type: 'EXPENSE',
      isRecurring: false,
      tags: ['uncategorized'],
    },
  ]

  const budgets = [
    {
      id: 'budget-housing',
      userId: DEMO_USER_ID,
      categoryId: 'cat-housing',
      name: 'Housing',
      amount: 1600,
      period: 'MONTHLY',
      startDate: toIso(daysAgo(20)),
      isActive: true,
      isRecurring: true,
      category: categories.find((category) => category.id === 'cat-housing'),
    },
    {
      id: 'budget-food',
      userId: DEMO_USER_ID,
      categoryId: 'cat-food',
      name: 'Food & Dining',
      amount: 650,
      period: 'MONTHLY',
      startDate: toIso(daysAgo(20)),
      isActive: true,
      isRecurring: true,
      category: categories.find((category) => category.id === 'cat-food'),
    },
    {
      id: 'budget-transport',
      userId: DEMO_USER_ID,
      categoryId: 'cat-transport',
      name: 'Transportation',
      amount: 220,
      period: 'MONTHLY',
      startDate: toIso(daysAgo(20)),
      isActive: true,
      isRecurring: true,
      category: categories.find((category) => category.id === 'cat-transport'),
    },
    {
      id: 'budget-entertainment',
      userId: DEMO_USER_ID,
      categoryId: 'cat-entertainment',
      name: 'Entertainment',
      amount: 180,
      period: 'MONTHLY',
      startDate: toIso(daysAgo(20)),
      isActive: true,
      isRecurring: true,
      category: categories.find(
        (category) => category.id === 'cat-entertainment'
      ),
    },
  ]

  const goals = [
    {
      id: 'goal-emergency',
      userId: DEMO_USER_ID,
      name: 'Emergency Fund',
      targetAmount: 5000,
      currentAmount: 2100,
      targetDate: toIso(daysFromNow(120)),
      color: '#22C55E',
      icon: '🛡️',
      isCompleted: false,
    },
    {
      id: 'goal-vacation',
      userId: DEMO_USER_ID,
      name: 'Summer getaway',
      targetAmount: 2200,
      currentAmount: 800,
      targetDate: toIso(daysFromNow(200)),
      color: '#F97316',
      icon: '✈️',
      isCompleted: false,
    },
  ]

  const subscriptions = [
    {
      id: 'sub-netflix',
      userId: DEMO_USER_ID,
      name: 'Netflix',
      amount: 16.99,
      currency: 'USD',
      billingCycle: 'MONTHLY',
      nextBillingDate: toIso(daysFromNow(5)),
      isActive: true,
      categoryId: 'cat-subscriptions',
    },
    {
      id: 'sub-spotify',
      userId: DEMO_USER_ID,
      name: 'Spotify',
      amount: 11.99,
      currency: 'USD',
      billingCycle: 'MONTHLY',
      nextBillingDate: toIso(daysFromNow(12)),
      isActive: true,
      categoryId: 'cat-subscriptions',
    },
    {
      id: 'sub-notion',
      userId: DEMO_USER_ID,
      name: 'Notion',
      amount: 8,
      currency: 'USD',
      billingCycle: 'MONTHLY',
      nextBillingDate: toIso(daysFromNow(2)),
      isActive: true,
      categoryId: 'cat-subscriptions',
    },
  ]

  const creditCards = [
    {
      id: 'cc-1',
      name: 'Chase Freedom Unlimited',
      balance: 2150,
      limit: 10000,
      apr: 18.99,
      dueDate: toIso(daysFromNow(8)).split('T')[0],
      lastStatement: toIso(daysAgo(28)).split('T')[0],
    },
    {
      id: 'cc-2',
      name: 'American Express Gold',
      balance: 980,
      limit: 15000,
      apr: 17.49,
      dueDate: toIso(daysFromNow(14)).split('T')[0],
      lastStatement: toIso(daysAgo(30)).split('T')[0],
    },
  ]

  return {
    accounts,
    categories,
    transactions,
    budgets,
    goals,
    subscriptions,
    creditCards,
  }
}
